Messages:
  Prefix: '&8[&2CReward&8] &r'
  claim: '&aReward claimed!'
  noClaim: '&cYou can not claim this reward yet! &7(%creward_time%)'
  configReload: '&7Config reloaded'
  reset: '&7%player_name%''s reward time has been reseted'
  noPerm: '&cYou do not have permission to execute this command'
  readyToClaim: '&aReady to claim!'
  notify: '&7You can claim &a%creward_amount% &7reward(s)!'
  autoPickup: '&7Auto-Claimed &a%rewards% &7reward(s) (Premium)'

# Auto picks up all rewards for player after joining
# If false, player gets only a notification
Autopickup:
  enabled: false
  permission: creward.autoclaim

# Should the GUI close after claiming a reward
closeOnClaim: true

# Aliases for the command
aliases:
  - /rewards
  - /daily

GUI:
  title: '&8Daily reward'
  rows: 5
  # Glass Filler for the GUI
  Filler:
    Enable: true
    Slots:
      - 0
      - 1
      - 2
      - 3
      - 4
    Item:
      Material: GRAY_STAINED_GLASS_PANE
  Rewards:
    # Cant be just a number! (ex. '5')
    # Will cause problems when using MySQL
    'daily':
      Item:
        # Reward claimable
        yesClaim:
          Item:
            Material: CHEST_MINECART
            #skullData: '%player_name%'
            glow: true
            Amount: 1
            Data: 0
            Title: '&aDaily reward'
            Lore:
              - ''
              - '&fClick to claim'
        # Waiting for reward
        noClaim:
          Item:
            Material: MINECART
            #skullData: '%player_name%'
            Amount: 1
            Data: 0
            Title: '&cDaily reward'
            Lore:
              - ''
              - '&7Come back again in &f%creward_time%'
        # No permission for reward
        noPermClaim:
          Item:
            Material: BARRIER
            #skullData: '%player_name%'
            Amount: 1
            Data: 0
            Title: '&cDaily reward'
            Lore:
              - ''
              - '&cNo permission'
      # Commands executed after claiming
      Commands:
        - give %player_name% diamond 64
        - give %player_name% golden_apple 2
      # Cooldown for the reward, in seconds
      Cooldown: 86400
      Slot: 10
      # Permission to claim this reward
      Permission: ''
  # Items for designing the GUI
  otherItems:
    'item1':
      Item:
        Material: BARRIER
        Data: 0
        #skullData: '%player_name%'
        Amount: 1
      Slot: 12

Sounds:
  OPEN_MENU:
    Sound: BLOCK_CHEST_OPEN
    Volume: 1
    Pitch: 4
  REWARD_PICKUP:
    Sound: ENTITY_CHICKEN_EGG
    Volume: 1
    Pitch: 4

MySQL:
  enable: false
  username: root
  password: ''
  adress: localhost:3306
  db: creward
